services:
  app:
    build:
      context: .
    ports:
      - "8082:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /etc/letsencrypt/live/chatbot.lopvet-damien.com/fullchain.pem:/etc/letsencrypt/live/chatbot.lopvet-damien.com/fullchain.pem    
      - /etc/letsencrypt/live/chatbot.lopvet-damien.com/privkey.pem:/etc/letsencrypt/live/chatbot.lopvet-damien.com/privkey.pem
    environment:
      - HTTPS=on
      - SSL_CERT_FILE=/etc/letsencrypt/live/chatbot.lopvet-damien.com/fullchain.pem
      - SSL_KEY_FILE=/etc/letsencrypt/live/chatbot.lopvet-damien.com/privkey.pem

    # entrypoint: npm run start
    # environment:
    #   - HTTPS=on
    #   - SSL_CERT_FILE=/etc/nginx/ssl/server.crt
    #   - SSL_KEY_FILE=/etc/nginx/ssl/server.key
